"""empty message

Revision ID: 663909c65923
Revises: 
Create Date: 2020-12-20 14:47:23.100315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663909c65923'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Inhabitant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('flat_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('items', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('inquirer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inquirer_id'], ['Inhabitant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Inquiry')
    op.drop_table('Inhabitant')
    # ### end Alembic commands ###
